name: "Build Lambda Package"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout do código do Lambda
        uses: actions/checkout@v4

      - name: Instalar dependências do Lambda
        run: npm install axios pg

      - name: Gerar o .zip do Lambda
        run: |
          zip -r zodh-authorizer.zip *

      - name: Salvar artefato do .zip
        uses: actions/upload-artifact@v3
        with:
          name: zodh-authorizer-zip
          path: zodh-authorizer.zip
