name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios pg aws-sdk

      - name: Zip code for Lambda
        run: zip -r zodh-authorizer.zip . -x "*.git*" "node_modules/aws-sdk/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Sign Up
        run: |
          aws lambda update-function-code \
            --function-name zodh-authorizer-sign-up \
            --zip-file fileb://zodh-authorizer.zip

      - name: Deploy to Sign In
        run: |
          aws lambda update-function-code \
            --function-name zodh-authorizer-sign-in \
            --zip-file fileb://zodh-authorizer.zip

      - name: Deploy to Confirmer
        run: |
          aws lambda update-function-code \
            --function-name zodh-authorizer-confirmer \
            --zip-file fileb://zodh-authorizer.zip
