name: "Build & Deploy Lambda to AWS"

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código do Lambda
        uses: actions/checkout@v4

      - name: Instalar dependências do Lambda
        run: npm install axios pg aws-sdk

      - name: Gerar o .zip do Lambda
        run: |
          zip -r zodh-authorizer.zip *

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Atualizar todas as funções Lambda na AWS
        run: |
          for function in zodh-authorizer-sign-up zodh-authorizer-confirmer zodh-authorizer-sign-in; do
            echo "Atualizando função: $function"
            aws lambda update-function-code \
              --function-name $function \
              --zip-file fileb://zodh-authorizer.zip
          done
