name: "Build & Deploy Lambda to AWS"

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout do código do Lambda
        uses: actions/checkout@v4

      - name: Instalar dependências do Lambda
        run: npm install axios pg aws-sdk

      - name: Gerar o .zip do Lambda
        run: |
          zip -r zodh-authorizer.zip *

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Atualizar função Lambda zodh-authorizer-sign-up
        run: |
          echo "Atualizando função: zodh-authorizer-sign-up"
          aws lambda update-function-code \
            --function-name zodh-authorizer-sign-up \
            --zip-file fileb://zodh-authorizer.zip

      - name: Atualizar função Lambda zodh-authorizer-confirmer
        run: |
          echo "Atualizando função: zodh-authorizer-confirmer"
          aws lambda update-function-code \
            --function-name zodh-authorizer-confirmer \
            --zip-file fileb://zodh-authorizer.zip

      - name: Atualizar função Lambda zodh-authorizer-sign-in
        run: |
          echo "Atualizando função: zodh-authorizer-sign-in"
          aws lambda update-function-code \
            --function-name zodh-authorizer-sign-in \
            --zip-file fileb://zodh-authorizer.zip
      
