name: "Deploy Lambda to AWS"

on:
  workflow_run:
    workflows: ["Build Lambda Package"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Baixar artefato gerado no workflow de build
        uses: actions/download-artifact@v3
        with:
          name: zodh-authorizer-zip
          path: ./artifact

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Atualizar funções Lambda na AWS
        run: |
          FUNCTIONS=("zodh-authorizer-sign-up" "zodh-authorizer-confirmer" "zodh-authorizer-sign-in")
          for function in "${FUNCTIONS[@]}"; do
            echo "Atualizando função: $function"
            aws lambda update-function-code \
              --function-name $function \
              --zip-file fileb://artifact/zodh-authorizer.zip \
              --publish  # Para garantir que a nova versão seja publicada
          done
